name: LÖVE Build

on:
  workflow_dispatch: # run workflow manually

jobs:
  love-build:
    name: Build release binaries of the game.
    runs-on: ubuntu-latest
    steps:
      - name: LÖVE Build
        uses: nhartland/love-build@v1-beta4
        with:
          app_name: 'Batteries not Included'
          love_version: '11.4'
          source_dir: '/src'
          result_dir: 'build'
